---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bluegreen-
spec:
  entrypoint: nightly-release
  serviceAccountName: argo-workflow       # created by Argo quick-start
  templates:
  - name: nightly-release
    dag:
      tasks:
      - name: lint
        template: lint

      - name: create-green
        dependencies: [lint]
        template: ansible
        arguments:
          parameters:
          - name: play
            value: create-green.yaml

      # TODO: add smoke-test, switch-traffic, etc.
      - name: smoke-test
        dependencies: [create-green]
        template: smoke-test

      - name: switch-traffic
        dependencies: [smoke-test]
        template: ansible
        when: "{{ tasks.smoke-test.status }} == Succeeded"
        arguments:
          parameters:
          - name: play
            value: switch-traffic.yaml
      # Is this needed? If smoke test fails it doesnt switch traffic
      - name: rollback
        dependencies: [smoke-test]
        template: rollback
        when: "{{tasks.smoke-test.status}} == 'Failed'"

  # --- generic template to run ansible-runner ------------------
  - name: ansible
    inputs:
      artifacts:
      - name: devops-hometask
        path: /devops-hometask
        git:
          repo: https://github.com/fbueno/devops-hometask.git
      parameters:
      - name: play
    container:
      image: quay.io/ansible/ansible-runner:latest
      command: [bash, -exc]
      workingDir: /devops-hometask
      args:
      - |
        pip3 install kubernetes pyyaml jsonpath
        ansible-galaxy collection install kubernetes.core
        ansible-runner run ansible -p {{inputs.parameters.play}}

  # --- lint ----------------------------------------------------
  - name: lint
    inputs:
      artifacts:
      - name: devops-hometask
        path: /devops-hometask
        git:
          repo: https://github.com/fbueno/devops-hometask.git
    script:
      image: python:3.12-alpine
      command: [sh]
      workingDir: /devops-hometask
      source: |
        pip install --quiet ansible-lint yamllint
        ansible-lint .
        yamllint -d relaxed .

  # --- smoke-test ----------------------------------------------------
  - name: smoke-test
    script:
      image: curlimages/curl
      command: [sh]
      source: |
        set -x
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x kubectl
        ips=$(./kubectl get pods -n default -l  release=green -o custom-columns=ip:.status.podIP --no-headers)
        for pod in $ips
        do
          echo "Smoke test pod $pod"
          curl --fail http://${pod}/ || exit $?
        done

  # --- rollback skeleton --------------------------------------
  - name: rollback
    dag:
      tasks:
      - name: cleanup
        template: ansible
        arguments:
          parameters:
          - name: play
            value: rollback.yaml
