---
# Playbook executed by Argo step "rollback"
# Inventory will be the Kubernetes cluster via the community.kubernetes collection
- name: Remove green deployment
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core
  vars:
    image_tag: plain-text
    app_name: demo-app
    release: blue
    old_release: green
  tasks:
    - name: "Switch traffic to {{ release }} deployment"
      kubernetes.core.k8s:
        state: patched
        kind: Service
        namespace: default
        name: "{{ app_name }}"
        definition:
          spec:
            selector:
              release: "{{ release }}"

    - name: "Register switched traffic to {{ release }} deployment"
      kubernetes.core.k8s_info:
        kind: Service
        namespace: default
        name: "{{ app_name }}"
      register: service_info

    - name: "Show switched traffic to {{ release }} deployment"
      debug:
        msg: "Service {{ app_name }} now points to {{ service_info.resources[0].spec.selector.release }}"
      when: service_info.resources | length > 0
      failed_when: service_info.resources | length == 0
      changed_when: false
    - name: Remove deploy
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}-{{ old_release }}"
        namespace: default
