---
# Playbook executed by Argo step "rollback"
# Inventory will be the Kubernetes cluster via the community.kubernetes collection
- name: Remove green deployment
  hosts: localhost
  gather_facts: false
  #no_log: true
  collections:
    - kubernetes.core
  vars:
    image_tag: plain-text
    app_name: demo-app
    release: blue
    old_release: green
  tasks:
    - name: Remove deploy
      kubernetes.core.k8s:
        state: absent
        api_version: apps/v1
        kind: Deployment
        name: "{{ app_name }}-{{ old_release }}"
        namespace: default

    - name: Wait for app to be removed
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: default
        name: "{{ app_name }}-{{ old_release }}"
        wait: true
        wait_sleep: 1
        wait_timeout: 120
      register: deployment_info
      until: deployment_info.resources is defined and (deployment_info.resources | length) == 0

    - name: "Switch traffic to {{ release }} deployment"
      kubernetes.core.k8s:
        state: patched
        kind: Service
        namespace: default
        name: "{{ app_name }}"
        definition:
          spec:
            selector:
              release: "{{ release }}"
